### ISSUE TITLE
Is use-snipcart 1.1.3  Outdated? 

### ISSUE THREAD

**Issue by lexsemenenko** [colbyfayock/use-snipcart#1]
I need to update my npm packages. use-snipcart didn't let me to update any package that depends on react. (React 18)

Also installing use-snipcart on up to date next.js project, gives me resolve errors. see picture attached. 

Please update the package to work with react 18 or help with a solution. Appreciate hugely

![CleanShot 2022-09-06 at 11 42 38@2x](https://user-images.githubusercontent.com/3987006/188678322-e52e85c6-9233-4c70-b1aa-d9768af1a8c0.jpg)

**Comment by colbyfayock** [comment]
hey i upgrade all the things and published `1.2.0`, can you check and see if that works for you? the demo seems to work properly!

**Comment by lexsemenenko** [comment]
Works! Confirm! All best!
